29_python-django-basics/hexlet-django-blog/hexlet_django_blog/articles/urls.py
from django.urls import path
from hexlet_django_blog.articles import views

app_name = 'articles'

urlpatterns = [
    path('', views.IndexView.as_view(), name='articles_index'),
    path('<int:id>/', views.articles_view, name='articles_view'),
]

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/categories/urls.py
from django.urls import path
from hexlet_django_blog.categories import views

urlpatterns = [
    path('', views.index),
]

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/urls.py
    
from django.urls import include, path
from hexlet_django_blog import views

urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('articles/', include('hexlet_django_blog.articles.urls', namespace='articles')),
    path('categories/', include('hexlet_django_blog.categories.urls')),
    path('admin/', admin.site.urls),
]

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/articles/models.py
from django.db import models


class Article(models.Model):
    name = models.CharField(max_length=200)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/articles/views.py
from django.http import Http404
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from django.views import View
from .models import Article


# @csrf_exempt
class IndexView(View):
    template_name = "articles/index.html"

    def get(self, request, *args, **kwargs):
        return self._render_articles()

    def post(self, request, *args, **kwargs):
        article_data = {
            'title': request.POST.get('title'),
            'author': request.POST.get('author'),
        }
        Article.objects.create(**article_data)
        return self._render_articles()

    def _render_articles(self, items_on_page=15):
        articles = Article.objects.all()[:items_on_page]
        return render(
            self.request,
            self.template_name,
            context={"articles": articles},
        )


@require_http_methods(['GET'])
def articles_view(request, id):
    # BEGIN (write your solution here)
    article = Article.objects.get(id=id)
    if not article:
        raise Http404()
    # END
    return render(request, 'articles/article.html', context={'article': article})

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/views.py
from django.shortcuts import render
from django.conf import settings

TEAM = [
    {'name': 'Yoda', 'position': 'CEO'},
    {'name': 'Obi-Wan Kenobi', 'position': 'Senior Developer'},
    {'name': 'Anakin Skywalker', 'position': 'Junior Developer'},
    {'name': 'Jar Jar Binks', 'position': 'Trainee'},
]


def index(request):
    print(settings.USERNAME)
    return render(
        request,
        'index.html',
        context={
            'username': settings.USERNAME,
            'password': settings.PASSWORD,
            }
    )

def about(request):
    return render(request, 'about.html')


def articles(request):
    return render(request, 'articles/index.html', context={'articles':{}})

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/templates/articles.html
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hexlet django blog</title>
    {% bootstrap_css %}
  </head>
  <body class="bg-light">
    <header>
      <div class="container mt-4">
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">Джанго Блог</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <a class="nav-link" href="/about/">О блоге</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/articles/">Статьи</a>
          <li>

          <li class="nav-item">
            <a class="nav-link" href="/categories/">Категории статей</a>
          </li>
        </ul>
        </div>
        </nav>
      </div>
    </header>
    <div class="container mt-4">
      <h1>Статьи</h1>
      <ul>
        {% for article in articles %}
        <li>{{ article.title }} by {{ article.author }}</li>
        {% endfor %}
      </ul>
    </div>
  </body>
</html>

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/templates/articles/article.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
<article>
  <h1 class="h2">{{ article.name }}</h1>
  <div>{{ article.body }}</div>
</article>
{% endblock %}

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/templates/articles/index.html
{% extends 'index.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block content %}
<h1>Статьи</h1>
<ul>
  {% for article in articles %}
    <div class="mb-3">
      <h2 class="h3">
        {{ article.name }}
      </h2>
      <div class="mb-0">{{ article.body|slice:":200" }}</div>
      <a href="{% url 'articles:articles_view' article.id %}">link</a>
    </div>
  </li>
  {% endfor %}
</ul>
{% endblock %}

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/templates/categories.html
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hexlet django blog</title>
    {% bootstrap_css %}
  </head>
  <body class="bg-light">
    <div class="container mt-4">
      <!-- BEGIN (write your solution here) -->
      <h1>Категории статей</h1>
      <!-- END -->
    </div>
  </body>
</html>

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/templates/index.html
{% extends './layout.html' %}
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

{% block navigation %}
{% include "./navigation.html" %}
{% endblock %}

{% block content %}
<h1>Мой Джанго Блог</h1>
<p>USERNAME is {{ username }}</p>
<p>PASSWORD is {{ password }}
{% endblock %}

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/templates/layout.html
{% load bootstrap4 %}
{% load i18n %}
{% get_current_language as LANGUAGE_CODE %}

<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Hexlet django blog blog</title>
    {% bootstrap_css %}
  </head>
  <body class="bg-light">
    <div class="container mt-4">
        <header>
            {% include "./navigation.html" %}
        </header>
      </div>

      <div class="container">
      <main>
        {% block content %}
        {% endblock %}
      </main>
      </div>
      </body>
</html>

29_python-django-basics/hexlet-django-blog/hexlet_django_blog/templates/navigation.html
{% block navigation %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="/">Джанго Блог</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

        <li class="nav-item">
        <!-- BEGIN (write your solution here) -->
          <a class="nav-link" href="{% url 'about' %}">About</a>
        <!-- END -->
        </li>

        <li class="nav-item">
        <!-- BEGIN (write your solution here) -->
          <a class="nav-link" href="{% url 'articles:articles_index' %}">Articles</a>
        <!-- END -->
        <li>
    </ul>
    </div>
</nav>
{% endblock %}